In [67]:
import pandas as pd

# Load the csv file
league_name = 'rbsc'  #'rpk', 'ifc', 'rbsc'
file_path = f'data/2024-2025/fact_gw_{league_name}.csv' # Replace with the path to your Excel file

# Read the data into a DataFrame
df = pd.read_csv(file_path)

In [68]:
# check 38 entries for every player
for no_of_entries in df.groupby('manager_id')['h2h_points'].count():
    assert no_of_entries == 38

In [69]:
# summarize total points and weekly pnl
def sum_pts_pnl(df, gw_start=1, gw_end=38):
    filtered_df = df[(df.gw_no >= gw_start) & (df.gw_no <= gw_end)]
    summary = filtered_df.groupby("name")[['h2h_points', 'pnl']].sum().sort_values(by='h2h_points', ascending=False)
    # add week range to first two columns
    summary['gw_start'] = gw_start
    summary['gw_end'] = gw_end
    # add rank
    summary['rank'] = summary['h2h_points'].rank(method='dense', ascending=False).astype(int)
    # rename columns for readability
    summary = summary.rename(columns={'h2h_points':'points', 'pnl':'weekly_pnl'})
    return summary

In [73]:
summary = sum_pts_pnl(df)
summary

                         points  weekly_pnl  gw_start  gw_end  rank
name
Roy Chayut                 2553           0         1      38     1
Akin Suriyabhivadh         2545        1000         1      38     2
Pannawit M                 2542         500         1      38     3
Arnon Porndhiti            2531        1000         1      38     4
Tae Uahwatanasakul         2508           0         1      38     5
Sutthapa Soonthornthum     2496        1000         1      38     6
Chuan Krub                 2495        1000         1      38     7
BooM Suriyabhivadh         2468         500         1      38     8
Natchanont Kraitrakul      2467         500         1      38     9
Pimadej Siwapornpitak      2463        1500         1      38    10
Nile Buranasiri            2456         500         1      38    11
Lemony Maaa                2456           0         1      38    11
songkram chaimongkol       2440         500         1      38    12
sirawat dulyavit           2435           0         1      38    13
Smith Mekaroonkamol        2427           0         1      38    14
Tone Na Ranong             2425        1500         1      38    15
Napin Surakkhaka           2417           0         1      38    16
Richy Very Much            2413        1000         1      38    17
Pow â€¦..                    2404           0         1      38    18
Nopnarit Lieopanich        2402           0         1      38    19
Palm S.                    2393           0         1      38    20
Tawiwut Charuwat           2378         500         1      38    21
Pum Lamsam                 2374         500         1      38    22
Pote V                     2369           0         1      38    23
Ayudh phonghanyudh         2354        -500         1      38    24
Gampanath Udomsorayuth     2342        -500         1      38    25
New Poshyananda            2334       -1000         1      38    26
Sarif Sainui               2332           0         1      38    27
Sira H                     2320         500         1      38    28
Kevin V                    2316           0         1      38    29
Nick Thanapoomikul         2309        1000         1      38    30
Guitar Raktakanit          2309        -500         1      38    30
James Rama                 2307           0         1      38    31
Teddy T                    2297        -500         1      38    32
Peep Chutrakul             2289         500         1      38    33
Pravi Techasith            2288           0         1      38    34
Tor Na Ranong              2286         500         1      38    35
Sirichai Jirapongphan      2257       -1000         1      38    36
Fung Niamkongkit           2255         500         1      38    37
sermwong tcfc              2247           0         1      38    38
Samote Viranuvatti         2240        1000         1      38    39
Garin Settachan            2238           0         1      38    40
Ekapan Ake                 2235           0         1      38    41
Wanwiwat Thongproh         2217       -1500         1      38    42
Nab Thavisin               2216           0         1      38    43
Gig ONEPOINT               2202         500         1      38    44
gub Na Songkhla            2189        -500         1      38    45
Tun Suraphongchai          2182       -1000         1      38    46
Kitti Traii                2165        -500         1      38    47
Bhuthong Thongyai          2149       -1000         1      38    48
Nopphanan Vannapanich      2144       -1500         1      38    49
Cobby Leathers             2134           0         1      38    50
Pradidthakorn Kasiwat      2116       -1500         1      38    51
Piyanut Rattanapian        2114       -2000         1      38    52
theerapat phuaphanthong    2108       -2500         1      38    53

In [ ]:
# add end of season prize 
def add_eos_prize(summary, prize: dict):
    summary_copy = summary.copy()
    # assign prize to rank
    summary_copy['end_of_season_prize'] = summary['rank'].map(prize).fillna(0).astype(int)
    #    assert summary_copy['end_of_season_prize'] == 0 # not applicable to ifc league because everybody paid upfront
    summary_copy['total_pnl'] = summary_copy['weekly_pnl'] + summary_copy['end_of_season_prize']
    return summary_copy

In [ ]:
# add_eos_prize(summary, {1:int(0.5*19000), 2:int(0.25*19000), 3:int(0.15*19000)}) # ifc
# add_eos_prize(summary, {1:3000, 2:2000, 3:1000, 6:-1000, 7:-2000, 8:-3000}) # rpk
add_eos_prize(summary, {1:int(0.5*19000), 2:int(0.25*19000), 3:int(0.15*19000)}) # rbsc

,points,weekly_pnl,gw_start,gw_end,rank,end_of_season_prize,total_pnl
name,,,,,,,
Tachapon Ratsameedara,2579,2250,1,38,1,3000,5250
Atthapon Parkart,2555,2550,1,38,2,2000,4550
Pattapong Charoenchaipong,2520,1800,1,38,3,1000,2800
sirawat dulyavit,2435,150,1,38,4,0,150
Tawiwut Charuwat,2378,-1000,1,38,5,0,-1000
Natthawat Charoenkitmongkol,2307,-1650,1,38,6,-1000,-2650
PHOOM T. YENBAMROONG,2299,-950,1,38,7,-2000,-2950
Nithiz Onkaewmanee,2203,-3150,1,38,8,-3000,-6150

In [79]:
def summarize_weekly_results(df: pd.DataFrame) -> pd.DataFrame:
    """
    Summarizes the number of weekly wins (rank == 1)
    and losses (rank == max in each gameweek) for each manager.

    This function does NOT mutate the original dataframe.

    Parameters:
        df (pd.DataFrame): The input dataframe containing at least
                           'gw_no', 'rank', 'manager_id', 'team_name', and 'name'.

    Returns:
        pd.DataFrame: Summary dataframe with weekly_wins and weekly_losses per manager.
    """
    # Work on a copy to avoid mutating the original
    df_copy = df.copy()

    # Compute the max rank per gw_no to identify weekly losers
    max_ranks = df_copy.groupby("gw_no")['rank'].transform('max')

    # Add boolean columns for weekly winners and losers
    df_copy['is_weekly_winner'] = df_copy['rank'] == 1
    df_copy['is_weekly_loser'] = df_copy['rank'] == max_ranks

    # Group by manager and count wins and losses
    summary = (
        df_copy.groupby(['name'])[['is_weekly_winner', 'is_weekly_loser']]
        .sum()
        .reset_index()
        .rename(columns={
            'is_weekly_winner': 'weekly_wins',
            'is_weekly_loser': 'weekly_losses'
        })
    )

    return summary.sort_values(by='weekly_wins', ascending=False)

In [81]:
summarize_weekly_results(df)

                       name  weekly_wins  weekly_losses
46           Tone Na Ranong            3              0
0        Akin Suriyabhivadh            2              0
42   Sutthapa Soonthornthum            2              0
1           Arnon Porndhiti            2              0
28    Pimadej Siwapornpitak            2              0
37       Samote Viranuvatti            2              1
11             Gig ONEPOINT            2              1
21       Nick Thanapoomikul            2              0
40    Sirichai Jirapongphan            1              3
39                   Sira H            1              0
44         Tawiwut Charuwat            1              0
36               Roy Chayut            1              1
22          Nile Buranasiri            1              0
35          Richy Very Much            1              0
34               Pum Lamsam            1              0
32    Pradidthakorn Kasiwat            1              4
29      Piyanut Rattanapian            1              5
47            Tor Na Ranong            1              0
53     songkram chaimongkol            1              0
26               Pannawit M            1              0
25                  Palm S.            1              1
24    Nopphanan Vannapanich            1              4
27           Peep Chutrakul            1              0
8          Fung Niamkongkit            1              0
6            Cobby Leathers            1              3
4        BooM Suriyabhivadh            1              0
5                Chuan Krub            1              0
54  theerapat phuaphanthong            1              6
19    Natchanont Kraitrakul            1              0
18         Napin Surakkhaka            1              1
16              Lemony Maaa            0              0
17             Nab Thavisin            0              0
2        Ayudh phonghanyudh            0              1
52         sirawat dulyavit            0              0
51            sermwong tcfc            0              0
50          gub Na Songkhla            0              1
49       Wanwiwat Thongproh            0              3
48        Tun Suraphongchai            0              2
3         Bhuthong Thongyai            0              2
45                  Teddy T            0              1
43       Tae Uahwatanasakul            0              0
41      Smith Mekaroonkamol            0              0
15              Kitti Traii            0              1
7                Ekapan Ake            0              0
20          New Poshyananda            0              2
38             Sarif Sainui            0              0
9    Gampanath Udomsorayuth            0              1
10          Garin Settachan            0              0
12        Guitar Raktakanit            0              1
13               James Rama            0              0
33          Pravi Techasith            0              0
14                  Kevin V            0              0
31                  Pow â€¦..            0              0
30                   Pote V            0              0
23      Nopnarit Lieopanich            0              0

In [ ]:
# visualization

In [78]:
5250+4550+2800+150-1000-2650-2950-6150

0